import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppProvider } from "../lib/AppContext";

const satoshi = localFont({
    src: [
        {
            path: "../public/fonts/Satoshi-Regular.otf",
            weight: "400",
            style: "normal",
        },
        {
            path: "../public/fonts/Satoshi-Medium.otf",
            weight: "500",
            style: "normal",
        },
        {
            path: "../public/fonts/Satoshi-Bold.otf",
            weight: "700",
            style: "normal",
        },
        {
            path: "../public/fonts/Satoshi-Black.otf",
            weight: "900",
            style: "normal",
        },
    ],
});

export const metadata: Metadata = {
    title: "Memes",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={satoshi.className}>
                <AppProvider>{children}</AppProvider>
            </body>
        </html>
    );
}
